import { FormEvent, useState } from 'react';
import { api } from '@appdeploy/client';
import { ArrowUpRight, Check, MapPin, Send, Users } from 'lucide-react';
import { MarkdownView } from './cms';

function submitForm(kind: string, form: Record<string, string>) { return api.post('/api/inquiries', { kind, ...form }); }

export function NewsletterSignup({ compact = false }: { compact?: boolean }) {
  const [email, setEmail] = useState(''); const [state, setState] = useState<'idle' | 'saving' | 'done' | 'error'>('idle');
  const submit = async (e: FormEvent) => { e.preventDefault(); setState('saving'); try { await api.post('/api/newsletter', { email, source: 'website' }); setState('done'); } catch { setState('error'); } };
  if (state === 'done') return <div className="newsletter-success"><Check size={17} /> You are on the list.</div>;
  return <form className={`newsletter-form ${compact ? 'compact' : ''}`} onSubmit={submit}><div><p className="eyebrow light">Stay in the loop</p>{!compact && <h3>Get the next Meet Up in your inbox.</h3>}</div><div className="newsletter-controls"><input type="email" value={email} onChange={e => setEmail(e.target.value)} placeholder="Your email address" required aria-label="Email address" /><button className="button cream" disabled={state === 'saving'}>{state === 'saving' ? 'Joining...' : 'Subscribe'} <Send size={16} /></button></div>{state === 'error' && <small role="alert">We could not subscribe you right now. Please try again.</small>}</form>;
}

export function StoriesPage({ page, stories }: { page?: Record<string, any>; stories: Array<Record<string, any>> }) {
  return <><section className="section page-intro"><div className="container narrow"><p className="eyebrow">{page?.eyebrow || 'Stories / Journal'}</p><h1>{page?.title || 'Stories from the Tribe.'}</h1><p className="lead">{page?.subtitle || 'Reflections, ideas and real moments that help community feel human.'}</p>{page?.bodyMarkdown && <MarkdownView markdown={page.bodyMarkdown} />}</div></section><section className="section"><div className="container story-list">{stories.length ? stories.map(story => <article className="journal-card" key={story.id || story.slug}><img src={story.image} alt={story.title} loading="lazy" decoding="async" /><div><span className="eyebrow">{story.category || 'Journal'}</span><h2>{story.title}</h2><p>{story.excerpt}</p><div className="journal-meta">{story.author || 'The Meet Up'} · {story.dateLabel || ''}</div><details><summary>Read story</summary><MarkdownView markdown={story.bodyMarkdown || ''} /></details></div></article>) : <div className="cms-empty-state"><h2>Stories are coming.</h2><p>New journal entries will appear here.</p></div>}</div></section><section className="cta-band"><div className="container cta-inner"><div><p className="eyebrow light">Keep connected</p><h2>There is always more to share.</h2></div><NewsletterSignup compact /></div></section></>;
}

export function LocationsPage({ page, locations }: { page?: Record<string, any>; locations: Array<Record<string, any>> }) {
  return <><section className="section page-intro"><div className="container narrow"><p className="eyebrow">{page?.eyebrow || 'Community Locations'}</p><h1>{page?.title || 'Find The Meet Up near you.'}</h1><p className="lead">{page?.subtitle || 'A multi-city architecture lets each chapter grow locally while staying connected to the wider Tribe.'}</p>{page?.bodyMarkdown && <MarkdownView markdown={page.bodyMarkdown} />}</div></section><section className="section"><div className="container location-grid">{locations.map(location => <article className="location-card" key={location.id || location.slug}><img src={location.image} alt={location.name} loading="lazy" decoding="async" /><div><span className={`location-status ${String(location.statusLabel || '').toLowerCase().includes('coming') ? 'soon' : ''}`}>{location.statusLabel}</span><h2>{location.name}</h2><p><MapPin size={16} /> {location.city}{location.country && location.country !== location.city ? `, ${location.country}` : ''}</p><p>{location.description}</p><button className="text-link" onClick={() => window.location.hash = 'join'}>Join the interest list <ArrowUpRight size={15} /></button></div></article>)}</div></section></>;
}

function EnquiryForm({ kind, title, intro }: { kind: 'volunteer' | 'partnership' | 'sponsorship'; title: string; intro: string }) {
  const [form, setForm] = useState({ name: '', email: '', phone: '', organisation: '', city: '', message: '' }); const [state, setState] = useState<'idle' | 'saving' | 'done' | 'error'>('idle');
  const submit = async (e: FormEvent) => { e.preventDefault(); setState('saving'); try { await submitForm(kind, form); setState('done'); } catch { setState('error'); } };
  if (state === 'done') return <div className="success-state"><div className="success-icon"><Check /></div><p className="eyebrow">Message received</p><h2>Thank you.</h2><p>We have your enquiry and will follow up with you.</p></div>;
  return <form className="enquiry-form" onSubmit={submit}><p className="form-title">{title}</p><p>{intro}</p><div className="form-grid"><label>Name<input value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} required /></label><label>Email<input type="email" value={form.email} onChange={e => setForm({ ...form, email: e.target.value })} required /></label><label>Phone / WhatsApp<input value={form.phone} onChange={e => setForm({ ...form, phone: e.target.value })} /></label><label>Organisation<input value={form.organisation} onChange={e => setForm({ ...form, organisation: e.target.value })} /></label><label>City<input value={form.city} onChange={e => setForm({ ...form, city: e.target.value })} /></label><label className="full-field">Message<textarea rows={5} value={form.message} onChange={e => setForm({ ...form, message: e.target.value })} required placeholder="Tell us what you have in mind." /></label></div>{state === 'error' && <div className="cms-message" role="alert">We could not send this right now. Please try again.</div>}<button className="button primary" disabled={state === 'saving'}>{state === 'saving' ? 'Sending...' : 'Send enquiry'} <ArrowUpRight /></button></form>;
}

export function VolunteerPage({ page }: { page?: Record<string, any> }) { return <><section className="section page-intro"><div className="container narrow"><p className="eyebrow">{page?.eyebrow || 'Volunteer'}</p><h1>{page?.title || 'Help build the community.'}</h1><p className="lead">{page?.subtitle || 'There is a lot that happens behind a great gathering. Tell us where you would love to contribute.'}</p>{page?.bodyMarkdown && <MarkdownView markdown={page.bodyMarkdown} />}</div></section><section className="section"><div className="container form-layout"><div><Users size={38} /><p className="eyebrow">Ways to contribute</p><h2>Bring what you are good at.</h2><p className="body-large">Hosting, photography, design, logistics, community care, music, communications and more can all make a difference.</p></div><div className="join-card"><EnquiryForm kind="volunteer" title="Volunteer interest" intro="Share your details and the kind of contribution you would enjoy making." /></div></div></section></>; }

export function PartnersPage({ page }: { page?: Record<string, any> }) { return <><section className="section page-intro"><div className="container narrow"><p className="eyebrow">{page?.eyebrow || 'Partnerships & Sponsorship'}</p><h1>{page?.title || 'Build with The Meet Up.'}</h1><p className="lead">{page?.subtitle || 'We are open to partnerships that create useful experiences, strengthen community and support sustainable growth.'}</p>{page?.bodyMarkdown && <MarkdownView markdown={page.bodyMarkdown} />}</div></section><section className="section"><div className="container partner-grid"><article className="partner-panel"><p className="eyebrow">Partnerships</p><h2>Let's create something meaningful together.</h2><p>For brands, organisations, creators and community builders interested in collaboration.</p><div className="join-card"><EnquiryForm kind="partnership" title="Partnership enquiry" intro="Tell us about your organisation and the collaboration you have in mind." /></div></article><article className="partner-panel"><p className="eyebrow">Sponsorship</p><h2>Support the next gathering.</h2><p>Sponsorship can help us create more accessible experiences, support community programming and expand into new cities.</p><div className="join-card"><EnquiryForm kind="sponsorship" title="Sponsorship enquiry" intro="Share your organisation, city and what you would like to support." /></div></article></div></section></>; }
